In [24]:
structure_file='data.vasp'
FC_file='FORCE_CONSTANTS_2ND'

In [25]:
from os import path
import sys

sys.path.append('../src')

Vx, Vy, Vz=get_Vij(structure_file,FC_file)


In [26]:
import numpy as np 
eigenvector=np.loadtxt('eigr.dat').reshape((24,24))
omega=np.loadtxt('freq.dat')

In [27]:
Sx,Sy,Sz=get_Sij(Vx,Vy,Vz,eigenvector,omega)

In [28]:
#check
GULP_Vijz=np.loadtxt('Vijz.dat').reshape((24,24))
np.where(np.abs(Vz-GULP_Vijz) > 0.001)

(array([], dtype=int64), array([], dtype=int64))

In [29]:
GULP_Vijy=np.loadtxt('Vijy.dat').reshape((24,24))
np.where(np.abs(Vy-GULP_Vijy) > 0.001)

(array([], dtype=int64), array([], dtype=int64))

In [30]:
GULP_Vijx=np.loadtxt('Vijx.dat').reshape((24,24))
np.where(np.abs(Vx-GULP_Vijx) > 0.001)

(array([], dtype=int64), array([], dtype=int64))

In [31]:
GULP_Sijx=np.loadtxt('Sijx.dat').reshape((24,24))
GULP_Sijy=np.loadtxt('Sijy.dat').reshape((24,24))
GULP_Sijz=np.loadtxt('Sijz.dat').reshape((24,24))
np.where(np.abs(Sx-GULP_Sijx) > 0.01)

(array([ 2,  2,  2,  2,  2,  2,  9, 12, 14, 15, 21, 22]),
 array([ 9, 12, 14, 15, 21, 22,  2,  2,  2,  2,  2,  2]))

システムの違いでどうしてもズレが出る

In [32]:
np.sum(np.abs(Sx-GULP_Sijx) )

0.604556369400741

In [33]:
np.where(np.abs(Sy-GULP_Sijy) > 0.1)

(array([ 2, 21]), array([21,  2]))

In [34]:
Sy[2]

array([ 0.00000000e+00, -0.00000000e+00, -1.61922382e-17,  7.18477546e+01,
        1.74766510e+02, -1.65249442e+02, -4.42425771e+01,  8.13632681e+00,
        1.42493180e+02, -6.76131435e+01, -2.97489709e+01,  1.24603810e+01,
       -5.87304130e+01, -1.86498842e+01,  1.09191898e+02, -2.18974177e+01,
        2.31502851e+02,  2.17869646e+02, -2.01147569e+02,  2.21005046e+02,
       -3.28542407e+01, -3.40444808e+03, -1.61679958e+00,  9.42591723e+01])

In [35]:
GULP_Sijy[2]

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  7.18349657e+01,
        1.74735402e+02, -1.65220028e+02, -4.42347020e+01,  8.13487854e+00,
        1.42467817e+02, -6.76011084e+01, -2.97436756e+01,  1.24581631e+01,
       -5.87199590e+01, -1.86465646e+01,  1.09172462e+02, -2.18935200e+01,
        2.31461643e+02,  2.17830865e+02, -2.01111765e+02,  2.20965708e+02,
       -3.28483926e+01, -3.40384209e+03, -1.61651179e+00,  9.42423942e+01])

In [36]:
np.sum(np.abs(Sz-GULP_Sijz) )

2.196118214102145

In [37]:
np.sum(np.abs(Sy-GULP_Sijy) )

1.9097769167402316

In [38]:
#mode diffusivity
#consider that frequency has cm-1 unit
#2pi of hbar is cancelled by this frequency definition

#Boltzmanns constant (J/K)
boltz = 1.38066244e-23

#Planck's constant (Js)
planck = 6.62617636e-34

#Speed of light (in cm/s)
speedl = 2.99792458e10

#eV -> Joules

evtoj = 1.6021917e-19

#Avogadros number
avogadro = 6.022045e23

In [39]:
fscale = np.sqrt(1.0e23*evtoj*avogadro)
fscale = fscale/(2.0*np.pi*speedl)

In [40]:
constant = ((1.0e-17*evtoj*avogadro)**0.5)*(fscale**3)
constant = np.pi*constant/48.0

In [41]:
constant

9.116410435342889

In [42]:
#get mean of frequency spacing
dwavg=0.0
for i in range(len(omega)-1):
    if omega[i] > 0.0:
        dwavg+=omega[i+1]-omega[i]
    elif omega[i+1] >0.0:
        dwavg+=omega[i+1]

dwavg=dwavg/(len(omega)-1)
dwavg

25.643677400657612

In [43]:
Di=np.zeros(len(omega))
nmodes=len(omega)
bfactor=5.0
broad = bfactor*dwavg
for i in range(nmodes):
    Di_loc = 0.0
    for j in range(nmodes):
        if(omega[i] > 0.01):
            dwij = (1.0/np.pi)*broad/( (omega[j] - omega[i])**2 + broad**2 )
            if(dwij > 0.01):
                Di_loc = Di_loc + dwij*Sx[j,i]**2+dwij*Sy[j,i]**2+dwij*Sz[j,i]**2
    Di[i] = Di[i] + Di_loc*constant/(omega[i]**2)

In [44]:
Di

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [45]:
from ase.io import read
atoms=read(structure_file,format='vasp')
vol = atoms.get_volume()
kappafct = 1.0e30/vol
temperature=300
cmfact = planck*speedl/(boltz*temperature)
for i in range(nmodes):
    xfreq = omega[i]*cmfact
    expfreq = np.exp(xfreq)
    cv_i = boltz*xfreq*xfreq*expfreq/(expfreq - 1.0)**2
    print(omega[i],Di[i]*1.0e4,cv_i*kappafct*Di[i])

-1.365903968777618e-05 0.0 0.0
-5.998889625991092e-06 0.0 0.0
1.429945356769956e-05 0.0 0.0
221.940168139047 0.0 0.0
221.940168139047 0.0 0.0
221.940168139047 0.0 0.0
221.940168139047 0.0 0.0
221.940168139047 0.0 0.0
221.940168139047 0.0 0.0
429.619338912949 0.0 0.0
429.619338912949 0.0 0.0
429.619338912949 0.0 0.0
429.61933891295 0.0 0.0
429.61933891295 0.0 0.0
429.61933891295 0.0 0.0
516.419660702354 0.0 0.0
516.419660702354 0.0 0.0
516.419660702354 0.0 0.0
516.419660702354 0.0 0.0
516.419660702354 0.0 0.0
516.419660702355 0.0 0.0
589.804580215125 0.0 0.0
589.804580215125 0.0 0.0
589.804580215125 0.0 0.0
