In [43]:
import numpy as np
import math

In [44]:
from ase.io import read
atoms=read('data.vasp',format='vasp')

#all atom is in central region by definition
#here we assume number of ghost shell is 1

#construct the list of vector connecting between each atoms

masses=atoms.get_masses()
natom=len(atoms.positions)

dist=np.zeros((natom,natom,3))
for i in range(natom):
    for j in range(natom):
        rmin=np.zeros(3)
        rij=atoms.get_distance(i,j,vector=True)
        rij_mic=atoms.get_distance(i,j,mic=True,vector=True)
        if(np.linalg.norm(rij_mic)<np.linalg.norm(rij)):
            rmin=rij_mic
        else:
            rmin=rij
        dist[i,j]=rmin

In [75]:
dist[:,:,0]

array([[ 0.    ,  0.    , -2.725 , -2.725 ,  1.3625,  1.3625, -1.3625,
        -1.3625],
       [ 0.    ,  0.    , -2.725 , -2.725 ,  1.3625,  1.3625, -1.3625,
        -1.3625],
       [ 2.725 ,  2.725 ,  0.    ,  0.    , -1.3625, -1.3625,  1.3625,
         1.3625],
       [ 2.725 ,  2.725 ,  0.    ,  0.    , -1.3625, -1.3625,  1.3625,
         1.3625],
       [-1.3625, -1.3625,  1.3625,  1.3625,  0.    ,  0.    ,  2.725 ,
         2.725 ],
       [-1.3625, -1.3625,  1.3625,  1.3625,  0.    ,  0.    ,  2.725 ,
         2.725 ],
       [ 1.3625,  1.3625, -1.3625, -1.3625, -2.725 , -2.725 ,  0.    ,
         0.    ],
       [ 1.3625,  1.3625, -1.3625, -1.3625, -2.725 , -2.725 ,  0.    ,
         0.    ]])

In [45]:
with open('FORCE_CONSTANTS_2ND','r') as fc:
    lines=fc.readlines()

    nlineblock=4
    fc_all=np.zeros((natom,natom,3,3))
    start=1
    for i in range(natom):
        for j in range(natom):
            fc_block=lines[start+1:start+nlineblock]
            fc=np.loadtxt(fc_block)
            fc_all[i,j]=fc/np.sqrt(masses[i]*masses[j])
            #fc_all[i,j]=fc
            start=start+nlineblock



In [46]:
fc_all[0,1]

array([[ 0.03913539, -0.        , -0.        ],
       [ 0.        , -0.00978188, -0.        ],
       [ 0.        , -0.        , -0.00978188]])

In [47]:
atoms.get_masses()

array([28.085, 28.085, 28.085, 28.085, 28.085, 28.085, 28.085, 28.085])

In [48]:
dist

array([[[ 0.    ,  0.    ,  0.    ],
        [ 0.    , -2.725 , -2.725 ],
        [-2.725 ,  0.    , -2.725 ],
        [-2.725 , -2.725 ,  0.    ],
        [ 1.3625,  1.3625,  1.3625],
        [ 1.3625, -1.3625, -1.3625],
        [-1.3625,  1.3625, -1.3625],
        [-1.3625, -1.3625,  1.3625]],

       [[ 0.    ,  2.725 ,  2.725 ],
        [ 0.    ,  0.    ,  0.    ],
        [-2.725 ,  2.725 ,  0.    ],
        [-2.725 ,  0.    ,  2.725 ],
        [ 1.3625, -1.3625, -1.3625],
        [ 1.3625,  1.3625,  1.3625],
        [-1.3625, -1.3625,  1.3625],
        [-1.3625,  1.3625, -1.3625]],

       [[ 2.725 ,  0.    ,  2.725 ],
        [ 2.725 , -2.725 ,  0.    ],
        [ 0.    ,  0.    ,  0.    ],
        [ 0.    , -2.725 ,  2.725 ],
        [-1.3625,  1.3625, -1.3625],
        [-1.3625, -1.3625,  1.3625],
        [ 1.3625,  1.3625,  1.3625],
        [ 1.3625, -1.3625, -1.3625]],

       [[ 2.725 ,  2.725 ,  0.    ],
        [ 2.725 ,  0.    , -2.725 ],
        [ 0.    ,  2.725 , -2.72

In [49]:
#slice for x-component
dist[:,:,0]

array([[ 0.    ,  0.    , -2.725 , -2.725 ,  1.3625,  1.3625, -1.3625,
        -1.3625],
       [ 0.    ,  0.    , -2.725 , -2.725 ,  1.3625,  1.3625, -1.3625,
        -1.3625],
       [ 2.725 ,  2.725 ,  0.    ,  0.    , -1.3625, -1.3625,  1.3625,
         1.3625],
       [ 2.725 ,  2.725 ,  0.    ,  0.    , -1.3625, -1.3625,  1.3625,
         1.3625],
       [-1.3625, -1.3625,  1.3625,  1.3625,  0.    ,  0.    ,  2.725 ,
         2.725 ],
       [-1.3625, -1.3625,  1.3625,  1.3625,  0.    ,  0.    ,  2.725 ,
         2.725 ],
       [ 1.3625,  1.3625, -1.3625, -1.3625, -2.725 , -2.725 ,  0.    ,
         0.    ],
       [ 1.3625,  1.3625, -1.3625, -1.3625, -2.725 , -2.725 ,  0.    ,
         0.    ]])

In [78]:
for i in range(natom):
    for j in range(i):
        print (i+1,j+1,dist[i,j,0])

2 1 0.0
3 1 2.7249999999999996
3 2 2.7249999999999996
4 1 2.7249999999999996
4 2 2.7249999999999996
4 3 0.0
5 1 -1.3625000000000007
5 2 -1.3625000000000007
5 3 1.3625000000000003
5 4 1.3625000000000003
6 1 -1.3625000000000007
6 2 -1.3625000000000007
6 3 1.3625000000000003
6 4 1.3625000000000003
6 5 0.0
7 1 1.3624999999999998
7 2 1.3624999999999998
7 3 -1.3624999999999998
7 4 -1.3624999999999998
7 5 -2.725
7 6 -2.725
8 1 1.3624999999999998
8 2 1.3624999999999998
8 3 -1.3624999999999998
8 4 -1.3624999999999998
8 5 -2.725
8 6 -2.725
8 7 0.0


In [50]:
Rx=dist[:,:,0]
Ry=dist[:,:,1]
Rz=dist[:,:,2]
Rx.shape, fc_all.shape

((8, 8), (8, 8, 3, 3))

コードをよく見ると、ix,jxの要素では負が入ってた。
当初比較していたのはFortran orderでのダンプだったので、列と行の順番が逆。

In [51]:
Vx=np.zeros((natom,natom,3,3))
Vy=np.zeros((natom,natom,3,3))
Vz=np.zeros((natom,natom,3,3))

for i in range(natom):
    for j in range(natom):
        Vijx=-Rx[i,j]*fc_all[i,j]
        Vx[i,j]=Vijx

        Vijy=-Ry[i,j]*fc_all[i,j]
        Vy[i,j]=Vijy

        Vijz=-Rz[i,j]*fc_all[i,j]
        Vz[i,j]=Vijz



In [52]:
#compare with GULP output
#1st atom x-direction component
Vx[0,:,0,:]

array([[-0.        ,  0.        ,  0.        ],
       [-0.        ,  0.        ,  0.        ],
       [-0.02665562,  0.        , -0.        ],
       [-0.02665562, -0.        ,  0.        ],
       [ 0.21791282,  0.13620392,  0.13620392],
       [ 0.21791282, -0.13620392, -0.13620392],
       [-0.21791282,  0.13620392, -0.13620392],
       [-0.21791282, -0.13620392,  0.13620392]])

GULP side
```
 ixyz:           1
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
 -2.665087135698760E-002  8.616184384773376E-017 -7.000649812628367E-017
 -2.665087135698760E-002 -7.000649812628367E-017  8.616184384773376E-017
  0.217874033757599       0.136179679902043       0.136179679902043     
  0.217874033757600      -0.136179679902044      -0.136179679902044     
 -0.217874033757599       0.136179679902043      -0.136179679902043     
 -0.217874033757599      -0.136179679902043       0.136179679902043    
```

In [53]:
#1st atom y-direction component
Vx[0,:,1,:]

array([[ 0.        , -0.        ,  0.        ],
       [-0.        ,  0.        ,  0.        ],
       [-0.        ,  0.10664395, -0.        ],
       [-0.        , -0.02665562,  0.        ],
       [ 0.13620392,  0.21791282,  0.13620392],
       [-0.13620392,  0.21791282,  0.13620392],
       [ 0.13620392, -0.21791282,  0.13620392],
       [-0.13620392, -0.21791282,  0.13620392]])

GULP
```
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
 -8.616184384773376E-017  0.106624964870440      -8.616184384773376E-017
 -7.000649812628367E-017 -2.665087135698760E-002  8.616184384773376E-017
  0.136179679902043       0.217874033757599       0.136179679902043     
 -0.136179679902044       0.217874033757600       0.136179679902043     
  0.136179679902043      -0.217874033757599       0.136179679902043     
 -0.136179679902043      -0.217874033757599       0.136179679902043   
```

In [54]:
Vx[7,:,2,:]

array([[-0.13620392, -0.13620392,  0.21791282],
       [ 0.13620392, -0.13620392,  0.21791282],
       [ 0.13620392, -0.13620392, -0.21791282],
       [-0.13620392, -0.13620392, -0.21791282],
       [ 0.        , -0.        ,  0.10664395],
       [-0.        , -0.        , -0.02665562],
       [ 0.        ,  0.        ,  0.        ],
       [-0.        ,  0.        , -0.        ]])

GULP
```
-0.136179679902043      -0.136179679902043       0.217874033757599     
  0.136179679902043      -0.136179679902043       0.217874033757599     
  0.136179679902043      -0.136179679902043      -0.217874033757599     
 -0.136179679902043      -0.136179679902043      -0.217874033757599     
  0.000000000000000E+000  5.385115240483360E-018 -0.106624964870440     
  3.231069144290016E-017  1.615534572145008E-017  2.665087135698754E-002
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
```

In [55]:
#y-component

Vy[0,:,0,:]

array([[-0.        ,  0.        ,  0.        ],
       [ 0.10664395, -0.        , -0.        ],
       [ 0.        , -0.        ,  0.        ],
       [-0.02665562, -0.        ,  0.        ],
       [ 0.21791282,  0.13620392,  0.13620392],
       [-0.21791282,  0.13620392,  0.13620392],
       [ 0.21791282, -0.13620392,  0.13620392],
       [-0.21791282, -0.13620392,  0.13620392]])

GULP
```
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.106624964870440      -8.616184384773376E-017 -8.616184384773376E-017
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
 -2.665087135698760E-002 -7.000649812628367E-017  8.616184384773376E-017
  0.217874033757599       0.136179679902043       0.136179679902043     
 -0.217874033757599       0.136179679902043       0.136179679902043     
  0.217874033757600      -0.136179679902044       0.136179679902043     
 -0.217874033757599      -0.136179679902043       0.136179679902043   
```

In [56]:
#z component
Vz[0,:,0,:]

array([[-0.        ,  0.        ,  0.        ],
       [ 0.10664395, -0.        , -0.        ],
       [-0.02665562,  0.        , -0.        ],
       [ 0.        ,  0.        , -0.        ],
       [ 0.21791282,  0.13620392,  0.13620392],
       [-0.21791282,  0.13620392,  0.13620392],
       [-0.21791282,  0.13620392, -0.13620392],
       [ 0.21791282,  0.13620392, -0.13620392]])

GULP
```
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.106624964870440      -8.616184384773376E-017 -8.616184384773376E-017
 -2.665087135698760E-002  8.616184384773376E-017 -7.000649812628367E-017
  0.000000000000000E+000  0.000000000000000E+000  0.000000000000000E+000
  0.217874033757599       0.136179679902043       0.136179679902043     
 -0.217874033757599       0.136179679902043       0.136179679902043     
 -0.217874033757599       0.136179679902043      -0.136179679902043     
  0.217874033757600       0.136179679902043      -0.136179679902044     
```

convert the shape of tensor to evaluate Sij with dot product with eigenvector

In [57]:
flatVx=np.reshape(Vx.transpose(0,2,1,3),(24,24))

In [58]:
flatVx[0]

array([-0.        ,  0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.02665562,  0.        , -0.        , -0.02665562,
       -0.        ,  0.        ,  0.21791282,  0.13620392,  0.13620392,
        0.21791282, -0.13620392, -0.13620392, -0.21791282,  0.13620392,
       -0.13620392, -0.21791282, -0.13620392,  0.13620392])

In [59]:
GULP_Vijx=np.loadtxt('Vijx.dat').reshape((24,24))

In [60]:
GULP_Vijx[0]

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -2.66508714e-02,  8.61618438e-17,
       -7.00064981e-17, -2.66508714e-02, -7.00064981e-17,  8.61618438e-17,
        2.17874034e-01,  1.36179680e-01,  1.36179680e-01,  2.17874034e-01,
       -1.36179680e-01, -1.36179680e-01, -2.17874034e-01,  1.36179680e-01,
       -1.36179680e-01, -2.17874034e-01, -1.36179680e-01,  1.36179680e-01])

In [66]:
np.unravel_index(np.argmax(flatVx-GULP_Vijx),flatVx.shape)

(19, 13)

In [67]:
flatVx[19]

array([-0.13620392,  0.21791282, -0.13620392,  0.13620392,  0.21791282,
       -0.13620392, -0.13620392, -0.21791282, -0.13620392,  0.13620392,
       -0.21791282, -0.13620392,  0.        ,  0.10664395, -0.        ,
       -0.        , -0.02665562, -0.        , -0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [68]:
GULP_Vijx[19]

array([-1.36179680e-01,  2.17874034e-01, -1.36179680e-01,  1.36179680e-01,
        2.17874034e-01, -1.36179680e-01, -1.36179680e-01, -2.17874034e-01,
       -1.36179680e-01,  1.36179680e-01, -2.17874034e-01, -1.36179680e-01,
        0.00000000e+00, -1.06624965e-01,  5.38511524e-18,  2.15404610e-17,
        2.66508714e-02,  1.07702305e-17,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00])

In [71]:
flatVy=np.reshape(Vy.transpose(0,2,1,3),(24,24))
GULP_Vijy=np.loadtxt('Vijy.dat').reshape((24,24))
np.where(np.abs(flatVy-GULP_Vijy) > 0.01)

(array([ 3,  4,  5,  6,  7,  8, 12, 12, 13, 13, 14, 14, 15, 16, 17, 18, 19,
        20, 21, 21, 22, 22, 23, 23]),
 array([ 6,  7,  8,  3,  4,  5, 15, 21, 16, 22, 17, 23, 12, 13, 14, 21, 22,
        23, 12, 18, 13, 19, 14, 20]))

In [72]:
flatVy[3]

array([-0.10664395, -0.        , -0.        , -0.        , -0.        ,
       -0.        ,  0.02665562, -0.        ,  0.        ,  0.        ,
        0.        , -0.        , -0.21791282,  0.13620392,  0.13620392,
        0.21791282,  0.13620392,  0.13620392, -0.21791282, -0.13620392,
        0.13620392,  0.21791282, -0.13620392,  0.13620392])

In [73]:
GULP_Vijy[3]

array([-1.06624965e-01, -8.61618438e-17, -8.61618438e-17,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -2.66508714e-02,  3.23106914e-17,
       -5.38511524e-17,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -2.17874034e-01,  1.36179680e-01,  1.36179680e-01,  2.17874034e-01,
        1.36179680e-01,  1.36179680e-01, -2.17874034e-01, -1.36179680e-01,
        1.36179680e-01,  2.17874034e-01, -1.36179680e-01,  1.36179680e-01])

In [63]:
flatVz=np.reshape(Vz.transpose(0,2,1,3),(24,24))
GULP_Vijz=np.loadtxt('Vijz.dat').reshape((24,24))
np.max(flatVz-GULP_Vijz)

0.21326891228761644