In [30]:
import phonopy

phonon = phonopy.load(supercell_matrix=[1, 1, 1],
                      primitive_matrix=[[1, 0, 0],
                                         [0, 1, 0],
                                         [0, 0, 1]],
                      unitcell_filename="POSCAR",
                      force_constants_filename="force_constants.hdf5")

In [31]:
print(phonon.primitive)

lattice:
- [     5.450000000000000,     0.000000000000000,     0.000000000000000 ] # a
- [     0.000000000000000,     5.450000000000000,     0.000000000000000 ] # b
- [     0.000000000000000,     0.000000000000000,     5.450000000000000 ] # c
points:
- symbol: Si # 1
  coordinates: [  0.875000000000000,  0.875000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 2
  coordinates: [  0.875000000000000,  0.375000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 3
  coordinates: [  0.375000000000000,  0.875000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 4
  coordinates: [  0.375000000000000,  0.375000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 5
  coordinates: [  0.125000000000000,  0.125000000000000,  0.125000000000000 ]
  mass: 28.085500
- symbol: Si # 6
  coordinates: [  0.125000000000000,  0.625000000000000,  0.625000000000000 ]
  mass: 28.085500
- symbol: Si # 7
  coordinates: [  0.625000000000000,  0.12500000000000

In [32]:
print(phonon.supercell)

lattice:
- [     5.450000000000000,     0.000000000000000,     0.000000000000000 ] # a
- [     0.000000000000000,     5.450000000000000,     0.000000000000000 ] # b
- [     0.000000000000000,     0.000000000000000,     5.450000000000000 ] # c
points:
- symbol: Si # 1
  coordinates: [  0.875000000000000,  0.875000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 2
  coordinates: [  0.875000000000000,  0.375000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 3
  coordinates: [  0.375000000000000,  0.875000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 4
  coordinates: [  0.375000000000000,  0.375000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 5
  coordinates: [  0.125000000000000,  0.125000000000000,  0.125000000000000 ]
  mass: 28.085500
- symbol: Si # 6
  coordinates: [  0.125000000000000,  0.625000000000000,  0.625000000000000 ]
  mass: 28.085500
- symbol: Si # 7
  coordinates: [  0.625000000000000,  0.12500000000000

In [33]:
mesh = [1, 1, 1]
phonon.run_mesh(mesh, with_eigenvectors=True)

In [34]:
mesh_dict = phonon.get_mesh_dict()
frequencies = mesh_dict['frequencies']
eigenvectors = mesh_dict['eigenvectors']

In [35]:
frequencies

array([[1.52040650e-07, 2.41322701e-07, 2.73252130e-07, 6.65389129e+00,
        6.65389129e+00, 6.65389129e+00, 6.65389129e+00, 6.65389129e+00,
        6.65389129e+00, 1.28808164e+01, 1.28808164e+01, 1.28808164e+01,
        1.28808164e+01, 1.28808164e+01, 1.28808164e+01, 1.54834050e+01,
        1.54834050e+01, 1.54834050e+01, 1.54834050e+01, 1.54834050e+01,
        1.54834050e+01, 1.76834046e+01, 1.76834046e+01, 1.76834046e+01]])

In [36]:
eigenvectors.shape

(1, 24, 24)

In [41]:
eigenvectors[0,:,0].reshape((8,3))

array([[-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j]])

In [42]:
eigenvectors[0,:,1].reshape((8,3))

array([[ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j]])

In [43]:
eigenvectors[0,:,4].reshape((8,3))

array([[ 0.04558229+0.j,  0.30842064+0.j, -0.29828543+0.j],
       [-0.04558229+0.j,  0.09408045+0.j,  0.21457884+0.j],
       [-0.09449635+0.j, -0.30842064+0.j, -0.21457884+0.j],
       [ 0.09449635+0.j, -0.09408045+0.j,  0.29828543+0.j],
       [-0.14926204+0.j,  0.02818602+0.j,  0.17679352+0.j],
       [ 0.14926204+0.j, -0.11189261+0.j,  0.22570757+0.j],
       [-0.36360223+0.j, -0.02818602+0.j, -0.22570757+0.j],
       [ 0.36360223+0.j,  0.11189261+0.j, -0.17679352+0.j]])

In [44]:
eigenvectors[0,:,23].reshape((8,3))

array([[-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j]])

縮退しているから固有ベクトルのとり方に任意性があってなかなか比較はしにくい。
frquencyは単位が違うので変換する