In [2]:
import phonopy

phonon = phonopy.load(supercell_matrix=[1, 1, 1],
                      primitive_matrix=[[1, 0, 0],
                                         [0, 1, 0],
                                         [0, 0, 1]],
                      unitcell_filename="POSCAR",
                      force_constants_filename="force_constants.hdf5")

primitive cellが自動で設定されないように手動で単位行列を入れておく

In [3]:
print(phonon.primitive)

lattice:
- [     5.450000000000000,     0.000000000000000,     0.000000000000000 ] # a
- [     0.000000000000000,     5.450000000000000,     0.000000000000000 ] # b
- [     0.000000000000000,     0.000000000000000,     5.450000000000000 ] # c
points:
- symbol: Si # 1
  coordinates: [  0.875000000000000,  0.875000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 2
  coordinates: [  0.875000000000000,  0.375000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 3
  coordinates: [  0.375000000000000,  0.875000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 4
  coordinates: [  0.375000000000000,  0.375000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 5
  coordinates: [  0.125000000000000,  0.125000000000000,  0.125000000000000 ]
  mass: 28.085500
- symbol: Si # 6
  coordinates: [  0.125000000000000,  0.625000000000000,  0.625000000000000 ]
  mass: 28.085500
- symbol: Si # 7
  coordinates: [  0.625000000000000,  0.12500000000000

In [4]:
print(phonon.supercell)

lattice:
- [     5.450000000000000,     0.000000000000000,     0.000000000000000 ] # a
- [     0.000000000000000,     5.450000000000000,     0.000000000000000 ] # b
- [     0.000000000000000,     0.000000000000000,     5.450000000000000 ] # c
points:
- symbol: Si # 1
  coordinates: [  0.875000000000000,  0.875000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 2
  coordinates: [  0.875000000000000,  0.375000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 3
  coordinates: [  0.375000000000000,  0.875000000000000,  0.375000000000000 ]
  mass: 28.085500
- symbol: Si # 4
  coordinates: [  0.375000000000000,  0.375000000000000,  0.875000000000000 ]
  mass: 28.085500
- symbol: Si # 5
  coordinates: [  0.125000000000000,  0.125000000000000,  0.125000000000000 ]
  mass: 28.085500
- symbol: Si # 6
  coordinates: [  0.125000000000000,  0.625000000000000,  0.625000000000000 ]
  mass: 28.085500
- symbol: Si # 7
  coordinates: [  0.625000000000000,  0.12500000000000

In [5]:
mesh = [1, 1, 1]
phonon.run_mesh(mesh, with_eigenvectors=True)

In [6]:
mesh_dict = phonon.get_mesh_dict()
frequencies = mesh_dict['frequencies']
eigenvectors = mesh_dict['eigenvectors']

In [7]:
frequencies

array([[1.52040650e-07, 2.41322701e-07, 2.73252130e-07, 6.65389129e+00,
        6.65389129e+00, 6.65389129e+00, 6.65389129e+00, 6.65389129e+00,
        6.65389129e+00, 1.28808164e+01, 1.28808164e+01, 1.28808164e+01,
        1.28808164e+01, 1.28808164e+01, 1.28808164e+01, 1.54834050e+01,
        1.54834050e+01, 1.54834050e+01, 1.54834050e+01, 1.54834050e+01,
        1.54834050e+01, 1.76834046e+01, 1.76834046e+01, 1.76834046e+01]])

In [8]:
eigenvectors.shape

(1, 24, 24)

In [9]:
eigenvectors[0,:,0].reshape((8,3))

array([[-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j],
       [-0.03287924+0.j, -0.07239675+0.j, -0.34449625+0.j]])

In [10]:
eigenvectors[0,:,1].reshape((8,3))

array([[ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j],
       [ 0.00406757+0.j, -0.34605068+0.j,  0.0723352 +0.j]])

In [11]:
eigenvectors[0,:,4].reshape((8,3))

array([[ 0.04558229+0.j,  0.30842064+0.j, -0.29828543+0.j],
       [-0.04558229+0.j,  0.09408045+0.j,  0.21457884+0.j],
       [-0.09449635+0.j, -0.30842064+0.j, -0.21457884+0.j],
       [ 0.09449635+0.j, -0.09408045+0.j,  0.29828543+0.j],
       [-0.14926204+0.j,  0.02818602+0.j,  0.17679352+0.j],
       [ 0.14926204+0.j, -0.11189261+0.j,  0.22570757+0.j],
       [-0.36360223+0.j, -0.02818602+0.j, -0.22570757+0.j],
       [ 0.36360223+0.j,  0.11189261+0.j, -0.17679352+0.j]])

In [12]:
eigenvectors[0,:,23].reshape((8,3))

array([[-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [-0.32754772+0.j,  0.00906384+0.j, -0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j],
       [ 0.32754772+0.j, -0.00906384+0.j,  0.13277928+0.j]])

縮退しているから固有ベクトルのとり方に任意性があってなかなか比較はしにくい。
frquencyは単位が違うので変換する

1THz=33.3 cm-1

In [13]:
√*33.3

array([[5.06295363e-06, 8.03604594e-06, 9.09929593e-06, 2.21574580e+02,
        2.21574580e+02, 2.21574580e+02, 2.21574580e+02, 2.21574580e+02,
        2.21574580e+02, 4.28931187e+02, 4.28931187e+02, 4.28931187e+02,
        4.28931187e+02, 4.28931187e+02, 4.28931187e+02, 5.15597387e+02,
        5.15597387e+02, 5.15597387e+02, 5.15597387e+02, 5.15597387e+02,
        5.15597387e+02, 5.88857373e+02, 5.88857373e+02, 5.88857373e+02]])

In [21]:
#Speed of light (in cm/s)
speedl = 2.99792458e10
import numpy as np
1/(speedl*1.0e-12)

33.35640951981521

In [22]:
frequencies*1/(speedl*1.0e-12)

array([[5.07153017e-06, 8.04965883e-06, 9.11470995e-06, 2.21949923e+02,
        2.21949923e+02, 2.21949923e+02, 2.21949923e+02, 2.21949923e+02,
        2.21949923e+02, 4.29657788e+02, 4.29657788e+02, 4.29657788e+02,
        4.29657788e+02, 4.29657788e+02, 4.29657788e+02, 5.16470798e+02,
        5.16470798e+02, 5.16470798e+02, 5.16470798e+02, 5.16470798e+02,
        5.16470798e+02, 5.89854886e+02, 5.89854886e+02, 5.89854886e+02]])

In [23]:
#planck constant eV s
planck=4.135667696e-15

In [24]:
THzTomev=planck*1.0e12*1.0e3
THzTomev

4.1356676960000005

In [29]:
cmtomeV=planck*(speedl)*1.0e3
cmtomeV

0.12398419840550369

In [30]:
1500*cmtomeV

185.97629760825552

```
!  Set constants
!
!  fscale is the conversion factor from (eV/Ang^2)(mol/g) in the dynamical matrix to
!  wavenumbers for the frequencies. The factor of 10^23 comes from Ang^2 -> m^2 and
!  g -> kg.
!
  fscale = sqrt(1.0d23*evtoj*avogadro)
  fscale = fscale/(2.0_dp*pi*speedl)
```

```
!*********************************
!  Eigenvectors and eigenvalues  *
!*********************************
      if (lgamma) then
!
!  Calculate eigenvalues and eigenvectors of uncorrected dynamical matrix
!
        call pdiagg(mcv,maxd2,derv2,eigr,freq(1,k-nlkpt+1),fscale,.true.,lprint,ifail)
```

```
!
!  Convert frequency units - imaginary freqs denoted by negative no.
!
  do i = 1,mcv
    root = freq(i)
    if (root.ge.0.0_dp) then
      freq(i) = sqrt(root)*fscale
    else
      root = abs(root)
      freq(i) = - sqrt(root)*fscale
    endif
  enddo
#ifdef TRACE
  call trace_out('pdiagg')
#endif
!
```